x-vulkan: &vulkan
  image: ghcr.io/ggml-org/llama.cpp:server-vulkan-b10964@sha256:43e0e25ca654d839ebda39fd6c2f200b36e9efb3e597ba90d0aaeff1be95ca53
  devices:
    - "${LLAMA_VULKAN_DEVICE:-/dev/dri/renderD128}:${LLAMA_VULKAN_DEVICE:-/dev/dri/renderD128}"

services:
  llama-server: *vulkan
  llama-embedding: *vulkan
