x-cuda: &cuda
  image: ghcr.io/ggml-org/llama.cpp:server-cuda-b10964@sha256:6cdceb771b5ab1b15acab46e9a235e4df4a138bfe1ca1ec9e531f061303b72b3
  gpus: all

services:
  llama-server: *cuda
  llama-embedding: *cuda
