kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.cri.v1.images".registry]
      [plugins."io.containerd.cri.v1.images".registry.mirrors]
        [plugins."io.containerd.cri.v1.images".registry.mirrors."docker.io"]
          endpoint = ["http://docker-registry-cache:5000", "https://registry-1.docker.io"]
        [plugins."io.containerd.cri.v1.images".registry.mirrors."quay.io"]
          endpoint = ["http://quay-registry-cache:5000", "https://quay.io"]
        [plugins."io.containerd.cri.v1.images".registry.mirrors."ghcr.io"]
          endpoint = ["http://ghcr-registry-cache:5000", "https://ghcr.io"]
networking:
  disableDefaultCNI: true
  podSubnet: 192.168.0.0/16
nodes:
  - role: control-plane
    image: kindest/node:v1.37.0@sha256:a1ed56cfb0e7b93589bdf97c8cd566405a265939e3620fc4f5de89adff580ae5
